name: Branchwise Deployment
on:
  push:
    branches:
      - main
      - dev
      - feature/*
  workflow_dispatch:
jobs:
  Development:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' && github.event_name == 'push'
    steps:
      - name: Dev_Checkout
        run: echo "Pushing to the dev branch..."

  Testing:
    runs-on: ubuntu-latest
    if: github.ref_name == 'feature/*' && github.event_name == 'push'
    steps:
      - name: Feature_Checkout
        run: echo "Pushing to a feature branch..."

  Production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.event_name == 'push'
    steps:
      - name: Main_Checkout
        run: echo "Pushing to the main branch..."

  Success_Notification:
    runs-on: ubuntu-latest
    needs: ['Development', 'Testing', 'Production']
    if: always()
    steps:
      - name: Notify_Success
        run: echo "Deployment to production successful!"

  Failure_Notification:
    runs-on: ubuntu-latest
    needs: ['Development', 'Testing', 'Production']
    if: failure()
    steps:
      - name: Notify_Failure
        run: echo "Deployment to production failed!"
